name: Push Mirror Repository
name: Push to Mirror

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_mirror:
    if: github.repository == vars.SHORT_REPO_URL
    name: Push to Mirror
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Mirror
        uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75
        with:
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          target_repo_url: ${{ secrets.MIRROR_URL }}
